### ISSUE TITLE
Please package testsuite to the distribution tarball

### ISSUE THREAD

**Issue by mcepl** [rocky/pycolumnize#29]
While packaging for openSUSE I found out that your release tarball does not contain the tests. Could you please distribute them as well?

**Comment by rocky** [comment]
It looks like this 15-year old code needs modernization. Yes, in the next iteration will include the tests.

Thanks for the patch, thanks for giving some context as to why this would be useful. A number of people don't, and then I have to assign the lowest priority for addressing when no background is given since I have so many other things to do.

**Comment by rocky** [comment]
@mcepl with release 0.3.11 there should now be tests. (Realizes that I this should have had a 1.0.0 release). 
Please double check though.

**Comment by mcepl** [comment]
Thanks, looks perfect.
